apiVersion: v1
kind: Namespace
metadata:
  name:  project1

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb-deploy
  namespace: project1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      imagePullSecrets:
        - name: my-docker-secret
      containers:
      - name: mariadb
        image: jeonghwan98/pro:${now} # 이미지 태그는 실제 빌드된 태그로 바뀜
        ports: 
        -  containerPort: 3306
        env:
        -  name: MY_SQL_ROOT_PASSWORD
           value: test123

---
apiVersion: v1
kind: Service
metadata:
  name: mariadb-svc
  namespace: project1
spec:
  selector:
    app: mariadb
  ports:
  - port: 3306
    targetPort: 3306
type: ClusterIP #외부에서 접속할 필요가 없으므로 LoadBalancer에서 ClusterIP로 변경