apiVersion: v1
kind: Namespace
metadata:
  name: project1

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy
  namespace: project1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      imagePullSecrets:
        - name: my-docker-secret
      containers:
        - name: nginx1
          image: jeonghwan98/pro:index.kia
          ports: 
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: web-svc
  namespace: project1
spec:
  selector:
    app: web
  ports:
    - port: 80
      targetPort: 80
  type: LoadBalancer
